/* GENERATED by scripts/capture-banners.mjs — do not edit by hand.
 *
 * The proportion (width / height) of each captured banner, so a tile can draw the whole shot at its
 * own width instead of cropping it to a fixed box. A banner is recognised by the arrangement across
 * its width, and a crop takes that away first. */
export const BANNER_SHOT_RATIO: Record<string, number> = {
  'scratch-h': 4.158,
  'scratch-v': 0.526,
  '3b2': 4.307,
  '3g': 2.571,
  '2a': 2.972,
  '5a': 1.9,
  '4b': 2.624,
  '3h': 3.746,
  '4d': 1.735,
  '3c': 4.095,
  '4f': 0.486,
  '4f2': 0.486,
  '4g': 0.787,
  '4e': 0.663,
};
